"use client";
import Providers from "@/lib/Providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout, Menu } from "antd";
import { Inter } from "next/font/google";
import React from "react";
import CustomLayout from "./CustomLayout";
import "./globals.css";

const { Header, Content, Footer, Sider } = Layout;
const { Item } = Menu;

type MenuItem = {
  key: string;
  icon: React.ReactNode;
  label: React.ReactNode;
  children?: MenuItem[];
};

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Detox-Dopamine ",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <AntdRegistry>
            <CustomLayout>{children}</CustomLayout>
          </AntdRegistry>
        </body>
      </html>
    </Providers>
  );
}
