"use client";
import NavBar from "@/components/structure/NavBar";
import Providers from "@/lib/Providers";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Detox-Dopamine ",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <AntdRegistry>
            <div className="mx-auto min-h-screen max-w-7xl">
              <NavBar />
              <div className="mx-auto max-w-6xl">{children}</div>
            </div>
          </AntdRegistry>
        </body>
      </html>
    </Providers>
  );
}
